"""Build a Ghidra Function ID database from reference binaries that carry symbols.

Function ID matches a function by hashing its instruction sequence with operands masked, so it
survives relocation and address changes but not a different inlining decision. That makes the
reference build the whole problem: to name functions in a shipped Unreal game, the database has to
come from an engine built the way the game was, and the names have to come from a PDB.

Give it one or more binaries with their PDBs beside them. It imports and analyses each into a
project folder shaped `<library>/<version>/<variant>`, which is the layout Ghidra's
CreateMultipleLibraries script expects, then populates a `.fidb` from the whole tree.

    python3 tools/ghidra/build-fid.py .local/ghidra/fid \\
        --binary ~/ue4/Blank-Win64-Shipping.exe --variant Shipping-Win64 \\
        --binary ~/ue4/Blank.exe --variant Development-Win64 \\
        --library UnrealEngine --release 4.18.3

Function ID analysis is switched off while ingesting, because matching against an existing database
while building one corrupts the names it records. That is what Ghidra's own pre-script does and why
it is used here rather than a plain analysis run.

A populated database says a function's bytes match a function that was named in the reference
build. It does not say the game's engine is unmodified, and a game with a patched engine will miss
exactly the functions someone changed.
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# CreateMultipleLibraries reads library, version and variant from three folder levels below its
# root, and the constant is not configurable from outside the script.
MASTER_DEPTH = 3

LANGUAGE_ID = "x86:LE:64:default"

FID_SCRIPTS = Path("Ghidra/Features/FunctionID/ghidra_scripts")
COMMON_SYMBOLS = Path("Ghidra/Features/FunctionID/data/common_symbols_win64.txt")


def headless(ghidra_home):
    launcher = ghidra_home / "support" / "analyzeHeadless"
    if not launcher.exists():
        raise SystemExit(f"no analyzeHeadless under {ghidra_home}")
    return launcher


def run(command, description):
    print(f"\n== {description}")
    print("   " + " ".join(str(part) for part in command))
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise SystemExit(f"{description} failed with exit code {result.returncode}")


def ingest(ghidra_home, project_dir, project, binary, folder, timeout):
    """Import one reference binary and analyse it with Function ID matching disabled."""
    if not binary.exists():
        raise SystemExit(f"no such binary: {binary}")
    symbols = binary.with_suffix(".pdb")
    if not symbols.exists():
        print(f"   warning: no {symbols.name} beside {binary.name}; "
              "without symbols this binary contributes no names")

    run([
        headless(ghidra_home), project_dir, f"{project}/{folder}",
        "-import", binary,
        "-overwrite",
        "-scriptPath", ghidra_home / FID_SCRIPTS,
        "-preScript", "FunctionIDHeadlessPrescript.java",
        "-postScript", "FunctionIDHeadlessPostscript.java",
        "-analysisTimeoutPerFile", str(timeout),
    ], f"import and analyse {binary.name} into {folder}")


def write_properties(directory, database, common_symbols, duplicates):
    """Answer CreateMultipleLibraries' prompts.

    Headless scripts read `askXxx` answers from a properties file whose key is the space separated
    concatenation of the prompt's title and message, with surrounding spaces stripped.
    """
    root = "/"
    lines = [
        "# Generated by tools/ghidra/build-fid.py. Keys are the script's prompt text.",
        f"Duplicate Results File OK = {duplicates}",
        "Do Duplication Detection Do you want to detect duplicates = yes",
        "Choose destination FidDB Please choose the destination FidDB for population = "
        f"{database}",
        f"Select root folder containing all libraries (at a depth of {MASTER_DEPTH}): = {root}",
        f"Common symbols file (optional): OK = {common_symbols}",
        f"Enter LanguageID To Process Language ID: = {LANGUAGE_ID}",
        "",
    ]
    path = directory / "CreateMultipleLibraries.properties"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("workspace", type=Path, help="untracked directory for project and database")
    parser.add_argument("--binary", action="append", type=Path, default=[], required=True,
                        help="reference binary; repeat once per variant")
    parser.add_argument("--variant", action="append", default=[],
                        help="variant name for the matching --binary, in the same order")
    parser.add_argument("--library", default="UnrealEngine", help="library name recorded in the database")
    parser.add_argument("--release", default="4.18.3", help="library version recorded in the database")
    parser.add_argument("--project", default="FidReference", help="Ghidra project name")
    parser.add_argument("--ghidra-home", type=Path,
                        default=Path(os.environ.get("GHIDRA_INSTALL_DIR", "/opt/ghidra")))
    parser.add_argument("--timeout", type=int, default=7200,
                        help="analysis timeout per binary in seconds")
    parser.add_argument("--skip-import", action="store_true",
                        help="only populate, reusing an already imported project")
    arguments = parser.parse_args()

    if arguments.variant and len(arguments.variant) != len(arguments.binary):
        raise SystemExit("give one --variant per --binary, in the same order")
    variants = arguments.variant or [path.stem for path in arguments.binary]

    ghidra_home = arguments.ghidra_home
    common_symbols = ghidra_home / COMMON_SYMBOLS
    if not common_symbols.exists():
        raise SystemExit(f"no common symbols file at {common_symbols}")

    workspace = arguments.workspace
    workspace.mkdir(parents=True, exist_ok=True)
    project_dir = workspace / "project"
    project_dir.mkdir(exist_ok=True)
    database = workspace / f"{arguments.library}-{arguments.release}.fidb"
    duplicates = workspace / "duplicates.txt"

    if not arguments.skip_import:
        for binary, variant in zip(arguments.binary, variants):
            folder = f"{arguments.library}/{arguments.release}/{variant}"
            ingest(ghidra_home, project_dir, arguments.project, binary, folder, arguments.timeout)

    # The database must exist and be registered as a user file before the populate step can offer
    # it as a destination. CreateEmptyFidDatabase takes the path as its only prompt.
    if database.exists():
        print(f"\n== reusing existing database {database}")
    else:
        run([
            headless(ghidra_home), project_dir, arguments.project,
            "-scriptPath", ghidra_home / FID_SCRIPTS,
            "-preScript", "CreateEmptyFidDatabase.java", str(database),
            "-noanalysis",
        ], f"create empty database {database.name}")

    properties_dir = workspace / "properties"
    properties_dir.mkdir(exist_ok=True)
    written = write_properties(properties_dir, database, common_symbols, duplicates)
    print(f"\n== populate answers written to {written}")

    run([
        headless(ghidra_home), project_dir, arguments.project,
        "-scriptPath", ghidra_home / FID_SCRIPTS,
        "-propertiesPath", properties_dir,
        "-postScript", "CreateMultipleLibraries.java",
        "-noanalysis",
    ], "populate the database from the imported tree")

    print()
    print(f"database   {database}")
    print(f"duplicates {duplicates}")
    print()
    print("Attach it in Ghidra through Tools -> Function ID -> Attach existing FidDB, then run the")
    print("Function ID analyzer on the target. Inspect ambiguous matches rather than trusting the")
    print("count: a match is a claim about bytes, not about the game's engine being unmodified.")


if __name__ == "__main__":
    if shutil.which("java") is None:
        print("warning: no java on PATH; Ghidra supplies its own if configured", file=sys.stderr)
    main()
