// SPDX-License-Identifier: GPL-3.0-only

#include <rescaleframe/d3d11_observer.h>
#include <rescaleframe/texture_dump.h>

#include <windows.h>

#include <d3d11.h>

#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

namespace {

// Vtable slots, from the table generated by tools/ghidra/build-directx-types.py.
constexpr size_t slot_create_buffer = 3;     // ID3D11Device
constexpr size_t slot_create_texture2d = 5;  // ID3D11Device
constexpr size_t slot_present = 8;           // IDXGISwapChain

using create_buffer_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*, const D3D11_BUFFER_DESC*,
                                                     const D3D11_SUBRESOURCE_DATA*,
                                                     ID3D11Buffer**);
using create_texture2d_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*,
                                                        const D3D11_TEXTURE2D_DESC*,
                                                        const D3D11_SUBRESOURCE_DATA*,
                                                        ID3D11Texture2D**);
using present_fn = HRESULT(STDMETHODCALLTYPE*)(IDXGISwapChain*, UINT, UINT);

struct Observer {
    std::mutex guard;
    bool installed = false;

    void** device_vtable = nullptr;
    void** swapchain_vtable = nullptr;
    create_texture2d_fn original_create = nullptr;
    create_buffer_fn original_create_buffer = nullptr;
    present_fn original_present = nullptr;

    rsf_observer_options options{};

    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    std::vector<ID3D11Texture2D*> matches;
    ID3D11Buffer* constants = nullptr;
    uint32_t constant_matches = 0;

    uint32_t frames = 0;
    uint32_t created = 0;
    uint32_t present_width = 0;
    uint32_t present_height = 0;
};

Observer& observer()
{
    static Observer instance;
    return instance;
}

bool patch_slot(void** vtable, size_t index, void* replacement, void** previous)
{
    DWORD protection = 0;
    if (!VirtualProtect(&vtable[index], sizeof(void*), PAGE_EXECUTE_READWRITE, &protection)) {
        return false;
    }
    if (previous) {
        *previous = vtable[index];
    }
    vtable[index] = replacement;
    DWORD restored = 0;
    VirtualProtect(&vtable[index], sizeof(void*), protection, &restored);
    return true;
}

bool interesting(const D3D11_TEXTURE2D_DESC& desc, const rsf_observer_options& options)
{
    if ((desc.BindFlags & D3D11_BIND_RENDER_TARGET) == 0) {
        return false;
    }
    if (options.format != 0 && desc.Format != static_cast<DXGI_FORMAT>(options.format)) {
        return false;
    }
    return desc.Width >= options.minimum_width;
}

HRESULT STDMETHODCALLTYPE hooked_create_texture2d(ID3D11Device* device,
                                                  const D3D11_TEXTURE2D_DESC* desc,
                                                  const D3D11_SUBRESOURCE_DATA* initial,
                                                  ID3D11Texture2D** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }

    // Nothing below calls into D3D11 while the lock is held. This hook runs inside the runtime's
    // own texture creation, so any D3D call made here can re-enter it, and re-entering a
    // non-recursive mutex deadlocks the process. Record only, and resolve the device later.
    std::lock_guard<std::mutex> lock(self.guard);
    ++self.created;
    if (self.matches.size() < self.options.capacity && interesting(*desc, self.options)) {
        // Hold a reference so the target stays alive to be dumped later. Only a handful match,
        // so this does not meaningfully change the game's memory behaviour.
        (*out)->AddRef();
        self.matches.push_back(*out);
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_buffer(ID3D11Device* device,
                                               const D3D11_BUFFER_DESC* desc,
                                               const D3D11_SUBRESOURCE_DATA* initial,
                                               ID3D11Buffer** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create_buffer(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }
    if (self.options.constant_buffer_bytes == 0 ||
        (desc->BindFlags & D3D11_BIND_CONSTANT_BUFFER) == 0 ||
        desc->ByteWidth != self.options.constant_buffer_bytes) {
        return result;
    }

    // Keep only the most recent match. The contents change every frame, so an old one would
    // describe a frame nobody asked about. Same rule as the other hooks: no D3D11 under the lock.
    ID3D11Buffer* previous = nullptr;
    (*out)->AddRef();
    {
        std::lock_guard<std::mutex> lock(self.guard);
        previous = self.constants;
        self.constants = *out;
        ++self.constant_matches;
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    if (previous) {
        previous->Release();
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_present(IDXGISwapChain* swapchain, UINT interval, UINT flags)
{
    Observer& self = observer();

    bool need_details = false;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        ++self.frames;
        need_details = self.present_width == 0;
    }

    // Queried outside the lock for the same re-entrancy reason as the creation hook.
    if (need_details) {
        DXGI_SWAP_CHAIN_DESC desc{};
        const bool described = SUCCEEDED(swapchain->GetDesc(&desc));
        ID3D11Device* device = nullptr;
        // A device reached this way covers the case where every texture predates installation.
        swapchain->GetDevice(__uuidof(ID3D11Device), reinterpret_cast<void**>(&device));

        std::lock_guard<std::mutex> lock(self.guard);
        if (described && self.present_width == 0) {
            self.present_width = desc.BufferDesc.Width;
            self.present_height = desc.BufferDesc.Height;
        }
        if (device) {
            if (!self.device) {
                self.device = device;
            } else {
                device->Release();
            }
        }
    }
    return self.original_present(swapchain, interval, flags);
}

// A dummy device and swap chain exist only to reach the vtables, which are shared by every
// instance the runtime creates. Once patched they can be released.
bool acquire_vtables(void*** device_vtable, void*** swapchain_vtable)
{
    WNDCLASSEXW window_class{};
    window_class.cbSize = sizeof(window_class);
    window_class.lpfnWndProc = DefWindowProcW;
    window_class.hInstance = GetModuleHandleW(nullptr);
    window_class.lpszClassName = L"RsfObserverProbe";
    RegisterClassExW(&window_class);
    HWND window = CreateWindowExW(0, window_class.lpszClassName, L"", WS_OVERLAPPEDWINDOW, 0, 0,
                                  8, 8, nullptr, nullptr, window_class.hInstance, nullptr);
    if (!window) {
        return false;
    }

    DXGI_SWAP_CHAIN_DESC desc{};
    desc.BufferCount = 1;
    desc.BufferDesc.Width = 8;
    desc.BufferDesc.Height = 8;
    desc.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    desc.OutputWindow = window;
    desc.SampleDesc.Count = 1;
    desc.Windowed = TRUE;

    IDXGISwapChain* swapchain = nullptr;
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    const D3D_FEATURE_LEVEL wanted[] = {D3D_FEATURE_LEVEL_11_0};
    D3D_FEATURE_LEVEL obtained{};
    HRESULT created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
                                                    wanted, 1, D3D11_SDK_VERSION, &desc,
                                                    &swapchain, &device, &obtained, &context);
    if (FAILED(created)) {
        created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0, wanted,
                                                1, D3D11_SDK_VERSION, &desc, &swapchain, &device,
                                                &obtained, &context);
    }
    if (FAILED(created) || !swapchain || !device) {
        DestroyWindow(window);
        return false;
    }

    *device_vtable = *reinterpret_cast<void***>(device);
    *swapchain_vtable = *reinterpret_cast<void***>(swapchain);

    if (context) {
        context->Release();
    }
    swapchain->Release();
    device->Release();
    DestroyWindow(window);
    return true;
}

} // namespace

extern "C" rsf_observer_result rsf_observer_install(const rsf_observer_options* options)
{
    if (!options || options->struct_size < sizeof(rsf_observer_options)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    if (options->abi_version != RSF_OBSERVER_ABI_VERSION) {
        return RSF_OBSERVER_ERROR_ABI_MISMATCH;
    }

    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (self.installed) {
        return RSF_OBSERVER_ERROR_ALREADY_INSTALLED;
    }

    self.options = *options;
    if (self.options.capacity == 0) {
        self.options.capacity = 16;
    }

    if (!acquire_vtables(&self.device_vtable, &self.swapchain_vtable)) {
        return RSF_OBSERVER_ERROR_NO_DEVICE;
    }

    if (!patch_slot(self.device_vtable, slot_create_texture2d,
                    reinterpret_cast<void*>(&hooked_create_texture2d),
                    reinterpret_cast<void**>(&self.original_create))) {
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    if (self.options.constant_buffer_bytes != 0 &&
        !patch_slot(self.device_vtable, slot_create_buffer,
                    reinterpret_cast<void*>(&hooked_create_buffer),
                    reinterpret_cast<void**>(&self.original_create_buffer))) {
        patch_slot(self.device_vtable, slot_create_texture2d,
                   reinterpret_cast<void*>(self.original_create), nullptr);
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    if (!patch_slot(self.swapchain_vtable, slot_present,
                    reinterpret_cast<void*>(&hooked_present),
                    reinterpret_cast<void**>(&self.original_present))) {
        patch_slot(self.device_vtable, slot_create_texture2d,
                   reinterpret_cast<void*>(self.original_create), nullptr);
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }

    self.installed = true;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_uninstall(void)
{
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (!self.installed) {
        return RSF_OBSERVER_ERROR_NOT_READY;
    }
    patch_slot(self.device_vtable, slot_create_texture2d,
               reinterpret_cast<void*>(self.original_create), nullptr);
    if (self.original_create_buffer) {
        patch_slot(self.device_vtable, slot_create_buffer,
                   reinterpret_cast<void*>(self.original_create_buffer), nullptr);
        self.original_create_buffer = nullptr;
    }
    patch_slot(self.swapchain_vtable, slot_present, reinterpret_cast<void*>(self.original_present),
               nullptr);
    for (ID3D11Texture2D* texture : self.matches) {
        texture->Release();
    }
    self.matches.clear();
    if (self.constants) {
        self.constants->Release();
        self.constants = nullptr;
    }
    if (self.context) {
        self.context->Release();
        self.context = nullptr;
    }
    if (self.device) {
        self.device->Release();
        self.device = nullptr;
    }
    self.installed = false;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_get_status(rsf_observer_status* status)
{
    if (!status || status->struct_size < sizeof(rsf_observer_status)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    status->installed = self.installed ? 1u : 0u;
    status->have_device = self.device != nullptr ? 1u : 0u;
    status->frames_presented = self.frames;
    status->textures_matched = static_cast<uint32_t>(self.matches.size());
    status->textures_created = self.created;
    status->present_width = self.present_width;
    status->present_height = self.present_height;
    status->constant_buffers_matched = self.constant_matches;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_dump_constants(const char* output_path_utf8,
                                                           uint32_t* bytes)
{
    if (!output_path_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();

    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    ID3D11Buffer* buffer = nullptr;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        if (!self.device || !self.constants) {
            return RSF_OBSERVER_ERROR_NOT_READY;
        }
        device = self.device;
        device->AddRef();
        buffer = self.constants;
        buffer->AddRef();
        context = self.context;
        if (context) {
            context->AddRef();
        }
    }
    if (!context) {
        device->GetImmediateContext(&context);
    }

    rsf_observer_result outcome = RSF_OBSERVER_ERROR_NOT_READY;
    if (context) {
        D3D11_BUFFER_DESC desc{};
        buffer->GetDesc(&desc);

        D3D11_BUFFER_DESC staging = desc;
        staging.Usage = D3D11_USAGE_STAGING;
        staging.BindFlags = 0;
        staging.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
        staging.MiscFlags = 0;

        ID3D11Buffer* readable = nullptr;
        if (SUCCEEDED(device->CreateBuffer(&staging, nullptr, &readable)) && readable) {
            context->CopyResource(readable, buffer);
            D3D11_MAPPED_SUBRESOURCE mapped{};
            if (SUCCEEDED(context->Map(readable, 0, D3D11_MAP_READ, 0, &mapped))) {
                if (std::FILE* stream = std::fopen(output_path_utf8, "wb")) {
                    std::fwrite(mapped.pData, 1, desc.ByteWidth, stream);
                    std::fclose(stream);
                    if (bytes) {
                        *bytes = desc.ByteWidth;
                    }
                    outcome = RSF_OBSERVER_OK;
                }
                context->Unmap(readable, 0);
            }
            readable->Release();
        }
        context->Release();
    }
    buffer->Release();
    device->Release();
    return outcome;
}

extern "C" rsf_observer_result rsf_observer_dump_matches(const char* output_prefix_utf8,
                                                         uint32_t view, uint32_t* written)
{
    if (!output_prefix_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();

    // Take a snapshot and let the lock go before touching D3D11. Dumping creates a staging
    // texture, which runs through this observer's own creation hook, and that hook takes the same
    // lock. Holding it across the dump deadlocks the caller against itself.
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    std::vector<ID3D11Texture2D*> snapshot;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        if (!self.device) {
            return RSF_OBSERVER_ERROR_NOT_READY;
        }
        device = self.device;
        device->AddRef();
        context = self.context;
        if (context) {
            context->AddRef();
        }
        snapshot = self.matches;
        for (ID3D11Texture2D* texture : snapshot) {
            texture->AddRef();
        }
    }

    if (!context) {
        // Resolved outside the lock for the same reason.
        device->GetImmediateContext(&context);
        if (context) {
            std::lock_guard<std::mutex> lock(self.guard);
            if (!self.context) {
                self.context = context;
                self.context->AddRef();
            }
        }
    }
    if (!context) {
        device->Release();
        for (ID3D11Texture2D* texture : snapshot) {
            texture->Release();
        }
        return RSF_OBSERVER_ERROR_NOT_READY;
    }

    uint32_t count = 0;
    for (size_t index = 0; index < snapshot.size(); ++index) {
        char prefix[1024];
        std::snprintf(prefix, sizeof(prefix), "%s_%zu", output_prefix_utf8, index);

        rsf_texture_dump_options dump{};
        dump.struct_size = sizeof(dump);
        dump.abi_version = RSF_TEXTURE_DUMP_ABI_VERSION;
        dump.output_prefix_utf8 = prefix;
        dump.view = view;
        if (rsf_dump_texture(device, context, snapshot[index], &dump, nullptr) == RSF_TEXTURE_OK) {
            ++count;
        }
    }

    for (ID3D11Texture2D* texture : snapshot) {
        texture->Release();
    }
    context->Release();
    device->Release();

    if (written) {
        *written = count;
    }
    return RSF_OBSERVER_OK;
}
