// SPDX-License-Identifier: GPL-3.0-only

#include <rescaleframe/d3d11_observer.h>
#include <rescaleframe/motion_decode.h>
#include <rescaleframe/texture_dump.h>

#include <windows.h>

#include <d3d11.h>

#include <MinHook.h>
#include <hde64.h>

#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <cwchar>
#include <mutex>
#include <string>
#include <vector>

namespace {

// Vtable slots, from the table generated by tools/ghidra/build-directx-types.py.
constexpr size_t slot_create_buffer = 3;     // ID3D11Device
constexpr size_t slot_create_texture2d = 5;  // ID3D11Device
constexpr size_t slot_create_input_layout = 11;   // ID3D11Device
constexpr size_t slot_create_vertex_shader = 12;  // ID3D11Device
constexpr size_t slot_create_pixel_shader = 15;   // ID3D11Device
constexpr size_t slot_present = 8;           // IDXGISwapChain

using create_buffer_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*, const D3D11_BUFFER_DESC*,
                                                     const D3D11_SUBRESOURCE_DATA*,
                                                     ID3D11Buffer**);
using create_texture2d_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*,
                                                        const D3D11_TEXTURE2D_DESC*,
                                                        const D3D11_SUBRESOURCE_DATA*,
                                                        ID3D11Texture2D**);
using present_fn = HRESULT(STDMETHODCALLTYPE*)(IDXGISwapChain*, UINT, UINT);
using create_input_layout_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*,
                                                           const D3D11_INPUT_ELEMENT_DESC*, UINT,
                                                           const void*, SIZE_T,
                                                           ID3D11InputLayout**);
using create_vertex_shader_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*, const void*, SIZE_T,
                                                            ID3D11ClassLinkage*,
                                                            ID3D11VertexShader**);
using create_pixel_shader_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*, const void*, SIZE_T,
                                                           ID3D11ClassLinkage*,
                                                           ID3D11PixelShader**);

struct Observer {
    std::mutex guard;
    bool installed = false;

    void** device_vtable = nullptr;
    void** swapchain_vtable = nullptr;
    create_texture2d_fn original_create = nullptr;
    create_buffer_fn original_create_buffer = nullptr;
    present_fn original_present = nullptr;
    // Present by detour, which is the route wherever the genuine function could be found.
    // `present_entry` is the function actually detoured: the outermost foreign hook's own function
    // when the entry of dxgi's Present is patched, dxgi's Present itself when it is not. See
    // `install_present_detour` for why it is never the patched entry.
    bool present_detoured = false;
    void* present_entry = nullptr;
    // MinHook's trampoline over the detoured function's own prologue: the rest of that function,
    // whatever it forwards to, and the genuine body at the end. Where this hook forwards.
    present_fn present_chain = nullptr;
    // A trampoline of this module's own over the bytes the file has for the entry, reaching the
    // genuine body without passing any hook. Where this forwards once another hook has re-patched
    // the entry over it, and the way out of a loop. Freed on uninstall.
    present_fn present_genuine = nullptr;
    void* present_genuine_block = nullptr;
    // The hook this displaced at the entry, for the log.
    void* present_displaced = nullptr;
    create_input_layout_fn original_create_input_layout = nullptr;
    create_vertex_shader_fn original_create_vertex_shader = nullptr;
    create_pixel_shader_fn original_create_pixel_shader = nullptr;

    rsf_observer_options options{};

    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    std::vector<ID3D11Texture2D*> matches;

    struct SizedBuffer {
        uint32_t bytes;
        ID3D11Buffer* buffer;
    };
    std::vector<SizedBuffer> constants;
    std::vector<std::pair<uint32_t, uint32_t>> buffer_sizes;  // size, times created
    uint32_t constant_matches = 0;

    // A dump requested from another thread, performed inside the next present.
    bool dump_pending = false;
    std::string dump_prefix;
    uint32_t dump_view = 0;
    uint32_t dumps_completed = 0;
    uint32_t textures_written = 0;
    uint32_t constant_bytes_written = 0;

    uint32_t frames = 0;
    uint32_t created = 0;
    uint32_t present_width = 0;
    uint32_t present_height = 0;
};

Observer& observer()
{
    static Observer instance;
    return instance;
}

bool patch_slot(void** vtable, size_t index, void* replacement, void** previous)
{
    DWORD protection = 0;
    if (!VirtualProtect(&vtable[index], sizeof(void*), PAGE_EXECUTE_READWRITE, &protection)) {
        return false;
    }
    if (previous) {
        *previous = vtable[index];
    }
    vtable[index] = replacement;
    DWORD restored = 0;
    VirtualProtect(&vtable[index], sizeof(void*), protection, &restored);
    return true;
}

bool interesting(const D3D11_TEXTURE2D_DESC& desc, const rsf_observer_options& options)
{
    if ((desc.BindFlags & D3D11_BIND_RENDER_TARGET) == 0) {
        return false;
    }
    if (options.format != 0 && desc.Format != static_cast<DXGI_FORMAT>(options.format)) {
        return false;
    }
    return desc.Width >= options.minimum_width;
}

HRESULT STDMETHODCALLTYPE hooked_create_texture2d(ID3D11Device* device,
                                                  const D3D11_TEXTURE2D_DESC* desc,
                                                  const D3D11_SUBRESOURCE_DATA* initial,
                                                  ID3D11Texture2D** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }

    // Nothing below calls into D3D11 while the lock is held. This hook runs inside the runtime's
    // own texture creation, so any D3D call made here can re-enter it, and re-entering a
    // non-recursive mutex deadlocks the process. Record only, and resolve the device later.
    std::lock_guard<std::mutex> lock(self.guard);
    ++self.created;
    // Every texture, not only the ones the dump filter retains: what a texture is for is the
    // caller's question, and the filter above exists to serve dumping rather than identification.
    if (self.options.on_texture) {
        self.options.on_texture(self.options.on_texture_user, *out, desc->Width, desc->Height,
                                static_cast<uint32_t>(desc->Format), desc->MipLevels,
                                desc->ArraySize, desc->SampleDesc.Count, desc->BindFlags,
                                desc->MiscFlags);
    }
    if (self.matches.size() < self.options.capacity && interesting(*desc, self.options)) {
        // Hold a reference so the target stays alive to be dumped later. Only a handful match,
        // so this does not meaningfully change the game's memory behaviour.
        (*out)->AddRef();
        self.matches.push_back(*out);
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_input_layout(ID3D11Device* device,
                                                     const D3D11_INPUT_ELEMENT_DESC* descs,
                                                     UINT count, const void* signature,
                                                     SIZE_T signature_bytes,
                                                     ID3D11InputLayout** out)
{
    Observer& self = observer();
    const HRESULT result =
        self.original_create_input_layout(device, descs, count, signature, signature_bytes, out);
    if (FAILED(result) || !descs || !out || !*out) {
        return result;
    }

    // Translated here rather than handed over raw, so the callback and its game-side rule never
    // need d3d11.h. Copied onto the stack because the descriptors belong to the caller.
    rsf_observer_layout_element elements[RSF_OBSERVER_MAX_LAYOUT_ELEMENTS];
    const uint32_t copied =
        count < RSF_OBSERVER_MAX_LAYOUT_ELEMENTS ? count : RSF_OBSERVER_MAX_LAYOUT_ELEMENTS;
    for (uint32_t index = 0; index < copied; ++index) {
        elements[index].semantic_index = descs[index].SemanticIndex;
        elements[index].format = static_cast<uint32_t>(descs[index].Format);
        elements[index].input_slot = descs[index].InputSlot;
        elements[index].byte_offset = descs[index].AlignedByteOffset;
        elements[index].per_instance =
            descs[index].InputSlotClass == D3D11_INPUT_PER_INSTANCE_DATA ? 1u : 0u;
    }

    std::lock_guard<std::mutex> lock(self.guard);
    if (self.options.on_layout) {
        self.options.on_layout(self.options.on_layout_user, *out, elements, copied, count);
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_vertex_shader(ID3D11Device* device, const void* bytecode,
                                                      SIZE_T bytes, ID3D11ClassLinkage* linkage,
                                                      ID3D11VertexShader** out)
{
    Observer& self = observer();
    const HRESULT result =
        self.original_create_vertex_shader(device, bytecode, bytes, linkage, out);
    if (FAILED(result) || !out || !*out) {
        return result;
    }
    std::lock_guard<std::mutex> lock(self.guard);
    if (self.options.on_shader) {
        self.options.on_shader(self.options.on_shader_user, *out, RSF_OBSERVER_STAGE_VERTEX,
                               bytecode, static_cast<uint32_t>(bytes));
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_pixel_shader(ID3D11Device* device, const void* bytecode,
                                                     SIZE_T bytes, ID3D11ClassLinkage* linkage,
                                                     ID3D11PixelShader** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create_pixel_shader(device, bytecode, bytes, linkage, out);
    if (FAILED(result) || !out || !*out) {
        return result;
    }
    std::lock_guard<std::mutex> lock(self.guard);
    if (self.options.on_shader) {
        self.options.on_shader(self.options.on_shader_user, *out, RSF_OBSERVER_STAGE_PIXEL,
                               bytecode, static_cast<uint32_t>(bytes));
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_buffer(ID3D11Device* device,
                                               const D3D11_BUFFER_DESC* desc,
                                               const D3D11_SUBRESOURCE_DATA* initial,
                                               ID3D11Buffer** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create_buffer(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }
    if (self.options.constant_buffer_max_bytes == 0 ||
        (desc->BindFlags & D3D11_BIND_CONSTANT_BUFFER) == 0) {
        return result;
    }
    const uint32_t bytes = desc->ByteWidth;

    ID3D11Buffer* previous = nullptr;
    bool retain = bytes >= self.options.constant_buffer_min_bytes &&
                  bytes <= self.options.constant_buffer_max_bytes;
    if (retain) {
        (*out)->AddRef();
    }
    {
        std::lock_guard<std::mutex> lock(self.guard);
        // Every size is counted, whether retained or not. When the stock size does not match,
        // this histogram is what identifies the right buffer for the next run.
        bool counted = false;
        for (auto& entry : self.buffer_sizes) {
            if (entry.first == bytes) {
                ++entry.second;
                counted = true;
                break;
            }
        }
        if (!counted && self.buffer_sizes.size() < 128) {
            self.buffer_sizes.emplace_back(bytes, 1u);
        }

        if (retain) {
            // Keep the most recent buffer of each distinct size. Contents change every frame, so
            // an older one would describe a frame nobody asked about.
            bool replaced = false;
            for (auto& entry : self.constants) {
                if (entry.bytes == bytes) {
                    previous = entry.buffer;
                    entry.buffer = *out;
                    replaced = true;
                    break;
                }
            }
            if (!replaced) {
                if (self.constants.size() < 16) {
                    self.constants.push_back({bytes, *out});
                } else {
                    previous = *out;  // nothing left to hold it in
                    retain = false;
                }
            }
            if (retain) {
                ++self.constant_matches;
            }
        }
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    if (previous) {
        previous->Release();
    }
    return result;
}

// Read without the lock, which is safe because options are written once during install and never
// again, and necessary because the interesting lines come from inside the dump loop.
void say(const Observer& self, const char* format, ...)
{
    if (!self.options.log) {
        return;
    }
    char message[512];
    va_list arguments;
    va_start(arguments, format);
    std::vsnprintf(message, sizeof(message), format, arguments);
    va_end(arguments);
    self.options.log(self.options.log_user, message);
}

// Decode one target the way a backend needs it, and write the result beside the raw dump.
//
// The pass is built and thrown away per texture rather than kept. This runs on a key press a few
// times a session, so the cost does not matter, and a cached pass would have to be invalidated
// whenever the render size changed, which is exactly what this project makes happen.
void decode_and_dump(Observer& self, ID3D11Device* device, ID3D11DeviceContext* context,
                     ID3D11Texture2D* source, const char* prefix)
{
    D3D11_TEXTURE2D_DESC description{};
    source->GetDesc(&description);

    rsf_motion_decode_setup setup{};
    setup.struct_size = sizeof(setup);
    setup.abi_version = RSF_MOTION_DECODE_ABI_VERSION;
    setup.width = description.Width;
    setup.height = description.Height;
    setup.log = self.options.log;
    setup.log_user = self.options.log_user;

    rsf_motion_decode* pass = nullptr;
    const rsf_motion_decode_result made = rsf_motion_decode_create(device, &setup, &pass);
    if (made != RSF_MOTION_DECODE_OK || !pass) {
        say(self, "motion decode unavailable, result %d", int(made));
        return;
    }

    rsf_motion_decode_params params{};
    params.struct_size = sizeof(params);
    params.scale_x = self.options.motion_scale;
    params.scale_y = self.options.motion_scale;
    params.bias_x = self.options.motion_bias;
    params.bias_y = self.options.motion_bias;
    params.output_scale_x = 1.0f;
    params.output_scale_y = 1.0f;
    params.invalid_value = self.options.motion_invalid_value;
    params.zero_means_unwritten = 1;

    const rsf_motion_decode_result ran = rsf_motion_decode_run(pass, context, source, &params);
    if (ran != RSF_MOTION_DECODE_OK) {
        say(self, "motion decode refused, result %d", int(ran));
        rsf_motion_decode_destroy(pass);
        return;
    }

    char path[1024];
    std::snprintf(path, sizeof(path), "%s_decoded", prefix);
    rsf_texture_dump_options dump{};
    dump.struct_size = sizeof(dump);
    dump.abi_version = RSF_TEXTURE_DUMP_ABI_VERSION;
    dump.output_prefix_utf8 = path;
    dump.view = RSF_DUMP_VIEW_DECODED_MOTION;
    dump.log = self.options.log;
    dump.log_user = self.options.log_user;
    rsf_dump_texture(device, context, rsf_motion_decode_texture(pass), &dump, nullptr);
    rsf_motion_decode_destroy(pass);
}

// Performed on the presenting thread, where using the immediate context is safe.
void perform_pending_dump(Observer& self)
{
    std::string prefix;
    uint32_t view = 0;
    std::vector<ID3D11Texture2D*> textures;
    std::vector<Observer::SizedBuffer> buffers;
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        if (!self.dump_pending || !self.device) {
            return;
        }
        self.dump_pending = false;
        prefix = self.dump_prefix;
        view = self.dump_view;
        textures = self.matches;
        buffers = self.constants;
        device = self.device;
        device->AddRef();
        context = self.context;
        if (context) {
            context->AddRef();
        }
        for (ID3D11Texture2D* texture : textures) {
            texture->AddRef();
        }
        for (auto& entry : buffers) {
            entry.buffer->AddRef();
        }
    }

    if (!context) {
        device->GetImmediateContext(&context);
        if (context) {
            std::lock_guard<std::mutex> lock(self.guard);
            if (!self.context) {
                self.context = context;
                self.context->AddRef();
            }
        }
    }

    uint32_t written = 0;
    uint32_t constant_bytes = 0;
    say(self, "dump begin: %zu textures, %zu constant buffers", textures.size(), buffers.size());
    if (context) {
        for (size_t index = 0; index < textures.size(); ++index) {
            char path[1024];
            std::snprintf(path, sizeof(path), "%s_%zu", prefix.c_str(), index);
            rsf_texture_dump_options dump{};
            dump.struct_size = sizeof(dump);
            dump.abi_version = RSF_TEXTURE_DUMP_ABI_VERSION;
            dump.output_prefix_utf8 = path;
            dump.view = view;
            dump.log = self.options.log;
            dump.log_user = self.options.log_user;
            say(self, "texture %zu of %zu", index + 1, textures.size());
            const rsf_dump_texture_result result =
                rsf_dump_texture(device, context, textures[index], &dump, nullptr);
            if (result == RSF_TEXTURE_OK) {
                ++written;
            } else {
                say(self, "texture %zu refused, result %d", index + 1, int(result));
            }

            if (self.options.decode_motion) {
                decode_and_dump(self, device, context, textures[index], path);
            }
        }

        for (const auto& entry : buffers) {
            say(self, "constant buffer of %u bytes", entry.bytes);
            // Same rule as for textures: a copy between resources of different devices is invalid
            // and crashes rather than failing.
            ID3D11Device* owner = nullptr;
            entry.buffer->GetDevice(&owner);
            const bool same_device = owner == device;
            if (owner) {
                owner->Release();
            }
            if (!same_device) {
                say(self, "constant buffer skipped, it belongs to another device");
                continue;
            }

            D3D11_BUFFER_DESC staging{};
            entry.buffer->GetDesc(&staging);
            staging.Usage = D3D11_USAGE_STAGING;
            staging.BindFlags = 0;
            staging.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
            staging.MiscFlags = 0;
            ID3D11Buffer* readable = nullptr;
            if (SUCCEEDED(device->CreateBuffer(&staging, nullptr, &readable)) && readable) {
                context->CopyResource(readable, entry.buffer);
                D3D11_MAPPED_SUBRESOURCE mapped{};
                if (SUCCEEDED(context->Map(readable, 0, D3D11_MAP_READ, 0, &mapped))) {
                    char path[1024];
                    std::snprintf(path, sizeof(path), "%s_cb%u.bin", prefix.c_str(), entry.bytes);
                    if (std::FILE* stream = std::fopen(path, "wb")) {
                        std::fwrite(mapped.pData, 1, entry.bytes, stream);
                        std::fclose(stream);
                        constant_bytes += entry.bytes;
                    }
                    context->Unmap(readable, 0);
                }
                readable->Release();
            }
        }
        context->Release();
    } else {
        say(self, "dump abandoned: no device context");
    }

    say(self, "dump end: %u textures, %u constant bytes", written, constant_bytes);
    for (ID3D11Texture2D* texture : textures) {
        texture->Release();
    }
    for (auto& entry : buffers) {
        entry.buffer->Release();
    }
    device->Release();

    std::lock_guard<std::mutex> lock(self.guard);
    ++self.dumps_completed;
    self.textures_written = written;
    self.constant_bytes_written = constant_bytes;
}

// Whether this thread is already inside the Present hook. Another hook chaining back into this
// one is the recursion `genuine_slot` exists to prevent; if it happens anyway, the inner call is
// refused rather than forwarded, which costs that frame and saves the process.
thread_local uint32_t present_depth = 0;

HRESULT STDMETHODCALLTYPE hooked_present(IDXGISwapChain* swapchain, UINT interval, UINT flags)
{
    Observer& self = observer();
    if (present_depth != 0) {
        static bool said = false;
        if (!said && self.options.log) {
            said = true;
            self.options.log(self.options.log_user,
                             "observer: Present re-entered from inside its own hook, so another "
                             "hook forwards to this one. The inner call goes straight to the "
                             "genuine Present where that is known, and is refused otherwise");
        }
        return self.present_detoured ? self.present_genuine(swapchain, interval, flags) : S_OK;
    }
    struct Depth {
        Depth() { ++present_depth; }
        ~Depth() { --present_depth; }
    } depth;

    bool need_details = false;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        ++self.frames;
        need_details = self.present_width == 0;
    }

    // Queried outside the lock for the same re-entrancy reason as the creation hook.
    // Recorded under the lock and reported outside it, because everything in this file is.
    void* replaced_device = nullptr;
    void* presenting_device = nullptr;
    // The presented size, from the swap chain on every present rather than once. AC7 creates its
    // window at the desktop's DPI-scaled size, 1707x1067 on a 2560x1600 desktop at 150 percent,
    // presents a few frames, and only then resizes the chain to the 1600x900 its settings say. A
    // size taken once at the first present was the wrong one for the whole run: DLSS was created
    // for an output that did not exist and every scene target failed the size judgement against it.
    {
        DXGI_SWAP_CHAIN_DESC desc{};
        if (SUCCEEDED(swapchain->GetDesc(&desc)) && desc.BufferDesc.Width != 0 &&
            (desc.BufferDesc.Width != self.present_width ||
             desc.BufferDesc.Height != self.present_height)) {
            std::lock_guard<std::mutex> lock(self.guard);
            const uint32_t previous_width = self.present_width;
            const uint32_t previous_height = self.present_height;
            self.present_width = desc.BufferDesc.Width;
            self.present_height = desc.BufferDesc.Height;
            if (previous_width != 0 && self.options.log) {
                char message[160];
                std::snprintf(message, sizeof(message),
                              "observer: the swap chain is now %ux%u, was %ux%u", self.present_width,
                              self.present_height, previous_width, previous_height);
                self.options.log(self.options.log_user, message);
            }
        }
    }
    if (need_details) {
        ID3D11Device* device = nullptr;
        // A device reached this way covers the case where every texture predates installation.
        swapchain->GetDevice(__uuidof(ID3D11Device), reinterpret_cast<void**>(&device));

        std::lock_guard<std::mutex> lock(self.guard);
        if (device) {
            /* The presenting device wins, always, even over one already chosen.

               A process can hold more than one D3D11 device. RenderDoc makes one, and so do some
               layers and middleware. `hooked_create_buffer` takes the first device that creates a
               constant buffer, which can easily be one of those rather than the game's, and until
               this ran only if nothing had been chosen yet, so a helper device chosen early was
               kept for the life of the process.

               Everything downstream then had the wrong device. It looked like it worked, because a
               device will happily compile shaders and allocate buffers of its own. It failed at
               exactly the point where one device has to touch another's resource: staging a copy of
               the game's view constant buffer refused every time, which read as a hundred thousand
               view read failures and no evaluations, and creating a view on the game's back buffer
               took the process down.

               The device that presents the frame is by definition the device that drew it. */
            if (self.device && self.device != device) {
                replaced_device = self.device;
                self.device->Release();
                self.device = nullptr;
                if (self.context) {
                    self.context->Release();
                    self.context = nullptr;
                }
            }
            if (!self.device) {
                self.device = device;
                presenting_device = device;
            } else {
                device->Release();
            }
        }
    }
    if (replaced_device && self.options.log) {
        char message[256];
        std::snprintf(message, sizeof(message),
                      "observer: the presenting device is %p, not the %p chosen earlier. Adopted "
                      "the presenting one; anything holding the other has the wrong device",
                      presenting_device, replaced_device);
        self.options.log(self.options.log_user, message);
    }
    perform_pending_dump(self);

    // Before the game's own Present, which is the one moment the finished frame exists and nothing
    // has been shown yet. No lock is held: this calls into D3D and back into the caller, and
    // holding one across that is how this project deadlocked twice.
    if (self.options.on_present) {
        self.options.on_present(self.options.on_present_user, swapchain);
    }
    if (!self.present_detoured) {
        return self.original_present(swapchain, interval, flags);
    }
    // Down the chain: the trampoline over the function this detoured, which continues into
    // whatever that function forwards to and ends in the genuine body. See
    // `install_present_detour` for why this is never a function whose entry someone re-asserts.
    return self.present_chain(swapchain, interval, flags);
}

// The function a module's own image has in a vtable slot, for a slot another hook has patched.
//
// Never forward to another hook. Measured on 26 September 2026, first Windows run: Steam's overlay
// (`gameoverlayrenderer64.dll`) hooks `IDXGISwapChain::Present` in the same table, notices when its
// entry is displaced, and re-hooks, taking whatever it displaced as its original. With this
// module's hook in the slot that made the two forward to each other, and every Present recursed
// until the stack ran out, sixty-four frames deep in the crash report. The genuine function is not
// in the table any more by then, but it is in the module on disk: the table is read-only data in
// `dxgi.dll`, so the slot's unrelocated value can be read from the file at the same RVA and
// relocated to the loaded base. `current` is what the slot held before this module patched it;
// it is returned as-is when it already lies inside the owning module.
// A module's file, read whole, with the module's loaded base and image size beside it.
struct ModuleImage {
    HMODULE module = nullptr;
    const unsigned char* base = nullptr;
    size_t image_size = 0;
    uint64_t preferred_base = 0;
    wchar_t path[MAX_PATH] = L"?";
    std::vector<unsigned char> bytes;
};

bool read_module_image(const void* inside, ModuleImage& out, char* message, size_t size)
{
    if (!GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                            static_cast<LPCWSTR>(inside), &out.module)) {
        std::snprintf(message, size, "%p is not inside any module", inside);
        return false;
    }
    out.base = reinterpret_cast<const unsigned char*>(out.module);
    const auto* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(out.base);
    const auto* headers = reinterpret_cast<const IMAGE_NT_HEADERS64*>(out.base + dos->e_lfanew);
    out.image_size = headers->OptionalHeader.SizeOfImage;
    if (!GetModuleFileNameW(out.module, out.path, MAX_PATH)) {
        std::snprintf(message, size, "the module's path could not be read");
        return false;
    }
    HANDLE file = CreateFileW(out.path, GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, 0,
                              nullptr);
    if (file == INVALID_HANDLE_VALUE) {
        std::snprintf(message, size, "%ls could not be opened", out.path);
        return false;
    }
    LARGE_INTEGER length{};
    if (GetFileSizeEx(file, &length) && length.QuadPart > 0 && length.QuadPart < (1 << 28)) {
        out.bytes.resize(static_cast<size_t>(length.QuadPart));
        DWORD read = 0;
        if (!ReadFile(file, out.bytes.data(), static_cast<DWORD>(out.bytes.size()), &read,
                      nullptr) ||
            read != out.bytes.size()) {
            out.bytes.clear();
        }
    }
    CloseHandle(file);
    if (out.bytes.size() < sizeof(IMAGE_DOS_HEADER)) {
        std::snprintf(message, size, "%ls could not be read", out.path);
        return false;
    }
    const auto* file_dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(out.bytes.data());
    if (static_cast<size_t>(file_dos->e_lfanew) + sizeof(IMAGE_NT_HEADERS64) > out.bytes.size()) {
        std::snprintf(message, size, "%ls has no usable headers", out.path);
        return false;
    }
    const auto* file_headers =
        reinterpret_cast<const IMAGE_NT_HEADERS64*>(out.bytes.data() + file_dos->e_lfanew);
    out.preferred_base = file_headers->OptionalHeader.ImageBase;
    return true;
}

// The file's bytes for `count` bytes at a loaded address, or null when no section covers them.
const unsigned char* disk_bytes(const ModuleImage& image, const void* address, size_t count)
{
    const auto* file_dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(image.bytes.data());
    const auto* file_headers =
        reinterpret_cast<const IMAGE_NT_HEADERS64*>(image.bytes.data() + file_dos->e_lfanew);
    const IMAGE_SECTION_HEADER* section = IMAGE_FIRST_SECTION(file_headers);
    const uintptr_t rva = static_cast<const unsigned char*>(address) - image.base;
    for (WORD index = 0; index < file_headers->FileHeader.NumberOfSections; ++index, ++section) {
        const uintptr_t start = section->VirtualAddress;
        const uintptr_t extent = section->Misc.VirtualSize > section->SizeOfRawData
                                     ? section->Misc.VirtualSize
                                     : section->SizeOfRawData;
        if (rva < start || rva + count > start + extent) {
            continue;
        }
        const size_t offset = rva - start + section->PointerToRawData;
        if (offset + count > image.bytes.size()) {
            return nullptr;
        }
        return image.bytes.data() + offset;
    }
    return nullptr;
}

void* genuine_slot(void** vtable, size_t slot, void* current, char* message, size_t size)
{
    ModuleImage image;
    if (!read_module_image(vtable, image, message, size)) {
        return nullptr;
    }
    const auto* candidate = static_cast<const unsigned char*>(current);
    if (candidate >= image.base && candidate < image.base + image.image_size) {
        return current;
    }
    const unsigned char* stored = disk_bytes(image, vtable + slot, sizeof(uint64_t));
    if (!stored) {
        std::snprintf(message, size, "no section of %ls covers the table", image.path);
        return nullptr;
    }
    uint64_t unrelocated = 0;
    std::memcpy(&unrelocated, stored, sizeof(unrelocated));
    if (unrelocated < image.preferred_base ||
        unrelocated - image.preferred_base >= image.image_size) {
        std::snprintf(message, size, "%ls holds 0x%llx in that slot, which is not inside it",
                      image.path, static_cast<unsigned long long>(unrelocated));
        return nullptr;
    }
    return const_cast<unsigned char*>(image.base + (unrelocated - image.preferred_base));
}

// The target and length of a jump another hook wrote at a function's entry. `bytes` are the
// entry's bytes, `entry` is where they live, which relative jumps are measured from. Null with a
// length of zero when the bytes are not a jump this recognises: the three forms hooking libraries
// write are a near jump, an indirect jump through a pointer after it, and a move into rax followed
// by a jump through it.
void* decode_jump(const unsigned char* bytes, const unsigned char* entry, size_t& length)
{
    if (bytes[0] == 0xE9) {
        int32_t displacement = 0;
        std::memcpy(&displacement, bytes + 1, sizeof(displacement));
        length = 5;
        return const_cast<unsigned char*>(entry + 5 + displacement);
    }
    if (bytes[0] == 0xFF && bytes[1] == 0x25) {
        int32_t displacement = 0;
        std::memcpy(&displacement, bytes + 2, sizeof(displacement));
        void* target = nullptr;
        std::memcpy(&target, entry + 6 + displacement, sizeof(target));
        length = 14;
        return target;
    }
    if (bytes[0] == 0x48 && bytes[1] == 0xB8 && bytes[10] == 0xFF && bytes[11] == 0xE0) {
        void* target = nullptr;
        std::memcpy(&target, bytes + 2, sizeof(target));
        length = 12;
        return target;
    }
    length = 0;
    return nullptr;
}

// Executable memory within a near jump of `near`, or null. Walks down from the address in
// allocation-granularity steps until the system gives a block, which is what a trampoline needs
// when the instructions it carries address memory relative to where they used to be.
void* allocate_near(const void* anchor, size_t size)
{
    SYSTEM_INFO info{};
    GetSystemInfo(&info);
    const uintptr_t granularity = info.dwAllocationGranularity ? info.dwAllocationGranularity
                                                                : 0x10000;
    const uintptr_t origin = reinterpret_cast<uintptr_t>(anchor) & ~(granularity - 1);
    const uintptr_t lowest = origin > 0x70000000 ? origin - 0x70000000 : granularity;
    for (uintptr_t candidate = origin - granularity; candidate > lowest;
         candidate -= granularity) {
        void* block = VirtualAlloc(reinterpret_cast<void*>(candidate), size,
                                   MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);
        if (block) {
            return block;
        }
    }
    return nullptr;
}

// A trampoline over a function's bytes as the file has them, so calling it reaches the function's
// body without passing anything patched at its entry.
//
// Copies whole instructions from the file's bytes until at least `covered` bytes are past, which
// has to be the longest patch anyone has at the entry, then jumps to the entry past that length.
// Instructions that address memory relative to the instruction pointer are re-pointed, which is
// why the block is allocated near; a relative jump or call this early in a function is refused,
// because relocating one is more than a prologue should need.
void* build_genuine_trampoline(const unsigned char* entry, const unsigned char* file_bytes,
                               size_t available, size_t covered, char* message, size_t size)
{
    constexpr size_t block_size = 64;
    auto* block = static_cast<unsigned char*>(allocate_near(entry, block_size));
    if (!block) {
        std::snprintf(message, size, "no executable memory near %p for a trampoline",
                      static_cast<const void*>(entry));
        return nullptr;
    }
    size_t copied = 0;
    while (copied < covered) {
        hde64s instruction{};
        const unsigned int length = hde64_disasm(file_bytes + copied, &instruction);
        if ((instruction.flags & F_ERROR) || length == 0 || copied + length > available ||
            copied + length > block_size - 14) {
            std::snprintf(message, size, "Present's prologue could not be decoded at byte %zu",
                          copied);
            VirtualFree(block, 0, MEM_RELEASE);
            return nullptr;
        }
        const unsigned char opcode = instruction.opcode;
        if (opcode == 0xE8 || opcode == 0xE9 || opcode == 0xEB || (opcode >= 0x70 && opcode <= 0x7F) ||
            (instruction.opcode2 >= 0x80 && instruction.opcode2 <= 0x8F && opcode == 0x0F) ||
            opcode == 0xC3 || opcode == 0xC2) {
            std::snprintf(message, size,
                          "Present's prologue has a relative jump or return at byte %zu, which "
                          "this does not relocate",
                          copied);
            VirtualFree(block, 0, MEM_RELEASE);
            return nullptr;
        }
        std::memcpy(block + copied, file_bytes + copied, length);
        if ((instruction.flags & F_MODRM) && (instruction.modrm & 0xC7) == 0x05) {
            // The displacement sits before any immediate, whose size the flags carry.
            const size_t immediate = (instruction.flags & 0x3C) >> 2;
            const size_t at = copied + length - immediate - 4;
            int32_t displacement = 0;
            std::memcpy(&displacement, block + at, sizeof(displacement));
            const intptr_t target =
                reinterpret_cast<intptr_t>(entry + copied + length) + displacement;
            const intptr_t moved = target - reinterpret_cast<intptr_t>(block + copied + length);
            if (moved > INT32_MAX || moved < INT32_MIN) {
                std::snprintf(message, size, "Present's prologue addresses memory too far from "
                                             "the trampoline");
                VirtualFree(block, 0, MEM_RELEASE);
                return nullptr;
            }
            displacement = static_cast<int32_t>(moved);
            std::memcpy(block + at, &displacement, sizeof(displacement));
        }
        copied += length;
    }
    // jmp [rip+0]; dq entry + copied
    const unsigned char jump[6] = {0xFF, 0x25, 0x00, 0x00, 0x00, 0x00};
    std::memcpy(block + copied, jump, sizeof(jump));
    const unsigned char* resume = entry + copied;
    std::memcpy(block + copied + sizeof(jump), &resume, sizeof(resume));
    FlushInstructionCache(GetCurrentProcess(), block, block_size);
    return block;
}

// The module a code address lives in, or null, with its file name for the log.
HMODULE module_of(const void* address, wchar_t* name, size_t count)
{
    HMODULE module = nullptr;
    if (!GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                                GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                            static_cast<LPCWSTR>(address), &module)) {
        return nullptr;
    }
    wchar_t path[MAX_PATH] = L"?";
    GetModuleFileNameW(module, path, MAX_PATH);
    const wchar_t* base = std::wcsrchr(path, L'\\');
    std::wcsncpy(name, base ? base + 1 : path, count - 1);
    name[count - 1] = L'\0';
    return module;
}

// Hook Present by detour, in a way that coexists with whatever else has hooked it.
//
// Measured on 26 September 2026, on a machine that turned out to have three hooks on dxgi's
// Present in a game: Steam's overlay, RivaTuner Statistics Server, and this. Each of the two others
// patches the function's entry with a jump and, on its first present, checks the entry and writes
// its own bytes back if something displaced them. Steam takes whatever it displaced as its
// original, which with a table patch of ours made the two forward to each other until the stack
// ran out; RivaTuner restores what it saved at its own install, which drops anything patched over
// it out of the chain entirely. Nothing patched at that entry can be trusted to stay.
//
// So this never owns the entry. It follows the jump chain from the entry to the first function
// that lives inside a module, which is the outermost hook's own function, or dxgi's Present itself
// when nothing is patched, and detours that. A hook re-asserts its target's entry; none re-asserts
// its own function's prologue. Steam and RivaTuner then run first, exactly as they would without
// this, and reach this hook through their own chains, which end in the genuine body.
//
// Two more pieces cover the rest: the chain is never entered twice by one present, because a
// re-entered call goes to a trampoline of this module's own over the bytes the file has for the
// entry, which reaches the body without passing any hook; and everything is put back on uninstall.
//
// Returns false with a reason when no target could be established; the caller then falls back to
// the table patch, with the re-entry guard as the only protection.
bool install_present_detour(Observer& self, void* genuine, char* message, size_t size)
{
    ModuleImage image;
    if (!read_module_image(genuine, image, message, size)) {
        return false;
    }
    constexpr size_t window = 32;
    const unsigned char* stored = disk_bytes(image, genuine, window);
    if (!stored) {
        std::snprintf(message, size, "no section of %ls covers Present", image.path);
        return false;
    }
    auto* entry = static_cast<unsigned char*>(genuine);
    const bool patched = std::memcmp(entry, stored, window) != 0;

    // The loop breaker, over the file's bytes. Fourteen bytes past the entry is beyond the longest
    // jump anyone writes there.
    void* block = build_genuine_trampoline(entry, stored, window, 14, message, size);
    if (!block) {
        return false;
    }

    // Follow the chain to the first function inside a module. Relays, the near pages hooking
    // libraries allocate to reach a far target with a short jump, are outside every module and are
    // followed through. This module's own hook is refused as a target, because meeting it would
    // mean something already chains to it.
    void* target = genuine;
    wchar_t owner[MAX_PATH] = L"dxgi.dll";
    size_t hops = 0;
    if (patched) {
        const unsigned char* at = entry;
        target = nullptr;
        for (hops = 0; hops < 8; ++hops) {
            size_t length = 0;
            void* next = decode_jump(at, at, length);
            if (!next) {
                break;
            }
            wchar_t name[MAX_PATH];
            HMODULE module = module_of(next, name, MAX_PATH);
            if (module) {
                if (next == reinterpret_cast<void*>(&hooked_present)) {
                    break;
                }
                target = next;
                std::wcsncpy(owner, name, MAX_PATH - 1);
                ++hops;
                break;
            }
            at = static_cast<const unsigned char*>(next);
        }
        if (!target) {
            VirtualFree(block, 0, MEM_RELEASE);
            std::snprintf(message, size,
                          "Present's entry is patched (%02x %02x %02x %02x %02x) and the chain "
                          "leads to no function inside a module",
                          entry[0], entry[1], entry[2], entry[3], entry[4]);
            return false;
        }
    }

    const MH_STATUS initialised = MH_Initialize();
    if (initialised != MH_OK && initialised != MH_ERROR_ALREADY_INITIALIZED) {
        VirtualFree(block, 0, MEM_RELEASE);
        std::snprintf(message, size, "MinHook did not initialise, status %d", int(initialised));
        return false;
    }
    void* chain = nullptr;
    MH_STATUS status = MH_CreateHook(target, reinterpret_cast<void*>(&hooked_present), &chain);
    if (status != MH_OK) {
        VirtualFree(block, 0, MEM_RELEASE);
        std::snprintf(message, size, "the detour on %ls could not be created, status %d", owner,
                      int(status));
        return false;
    }
    status = MH_EnableHook(target);
    if (status != MH_OK) {
        MH_RemoveHook(target);
        VirtualFree(block, 0, MEM_RELEASE);
        std::snprintf(message, size, "the detour on %ls could not be enabled, status %d", owner,
                      int(status));
        return false;
    }
    self.present_entry = target;
    self.present_chain = reinterpret_cast<present_fn>(chain);
    self.present_genuine = reinterpret_cast<present_fn>(block);
    self.present_genuine_block = block;
    self.present_displaced = patched ? target : nullptr;
    self.present_detoured = true;

    if (self.options.log) {
        char note[512];
        if (patched) {
            std::snprintf(note, sizeof(note),
                          "observer: Present's entry at %p is hooked by others; detoured the "
                          "outermost hook's function at %p in %ls, %zu hop%s down the chain, so it "
                          "runs first and this runs after it. Genuine body at hand through a "
                          "trampoline at %p",
                          genuine, target, owner, hops, hops == 1 ? "" : "s", block);
        } else {
            std::snprintf(note, sizeof(note),
                          "observer: Present detoured at %p in dxgi, entry unpatched", genuine);
        }
        self.options.log(self.options.log_user, note);
    }
    return true;
}

// A dummy device and swap chain exist only to reach the vtables, which are shared by every
// instance the runtime creates. Once patched they can be released.
bool acquire_vtables(void*** device_vtable, void*** swapchain_vtable)
{
    WNDCLASSEXW window_class{};
    window_class.cbSize = sizeof(window_class);
    window_class.lpfnWndProc = DefWindowProcW;
    window_class.hInstance = GetModuleHandleW(nullptr);
    window_class.lpszClassName = L"RsfObserverProbe";
    RegisterClassExW(&window_class);
    HWND window = CreateWindowExW(0, window_class.lpszClassName, L"", WS_OVERLAPPEDWINDOW, 0, 0,
                                  8, 8, nullptr, nullptr, window_class.hInstance, nullptr);
    if (!window) {
        return false;
    }

    DXGI_SWAP_CHAIN_DESC desc{};
    desc.BufferCount = 1;
    desc.BufferDesc.Width = 8;
    desc.BufferDesc.Height = 8;
    desc.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    desc.OutputWindow = window;
    desc.SampleDesc.Count = 1;
    desc.Windowed = TRUE;

    IDXGISwapChain* swapchain = nullptr;
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    const D3D_FEATURE_LEVEL wanted[] = {D3D_FEATURE_LEVEL_11_0};
    D3D_FEATURE_LEVEL obtained{};
    HRESULT created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
                                                    wanted, 1, D3D11_SDK_VERSION, &desc,
                                                    &swapchain, &device, &obtained, &context);
    if (FAILED(created)) {
        created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0, wanted,
                                                1, D3D11_SDK_VERSION, &desc, &swapchain, &device,
                                                &obtained, &context);
    }
    if (FAILED(created) || !swapchain || !device) {
        DestroyWindow(window);
        return false;
    }

    *device_vtable = *reinterpret_cast<void***>(device);
    *swapchain_vtable = *reinterpret_cast<void***>(swapchain);

    if (context) {
        context->Release();
    }
    swapchain->Release();
    device->Release();
    DestroyWindow(window);
    return true;
}

} // namespace

extern "C" rsf_observer_result rsf_observer_install(const rsf_observer_options* options)
{
    if (!options || options->struct_size < sizeof(rsf_observer_options)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    if (options->abi_version != RSF_OBSERVER_ABI_VERSION) {
        return RSF_OBSERVER_ERROR_ABI_MISMATCH;
    }

    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (self.installed) {
        return RSF_OBSERVER_ERROR_ALREADY_INSTALLED;
    }

    self.options = *options;
    if (self.options.capacity == 0) {
        self.options.capacity = 16;
    }

    if (!acquire_vtables(&self.device_vtable, &self.swapchain_vtable)) {
        return RSF_OBSERVER_ERROR_NO_DEVICE;
    }

    if (!patch_slot(self.device_vtable, slot_create_texture2d,
                    reinterpret_cast<void*>(&hooked_create_texture2d),
                    reinterpret_cast<void**>(&self.original_create))) {
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    if (self.options.constant_buffer_max_bytes != 0 &&
        !patch_slot(self.device_vtable, slot_create_buffer,
                    reinterpret_cast<void*>(&hooked_create_buffer),
                    reinterpret_cast<void**>(&self.original_create_buffer))) {
        patch_slot(self.device_vtable, slot_create_texture2d,
                   reinterpret_cast<void*>(self.original_create), nullptr);
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    // Present by detour on the genuine function, which the table names directly or, when another
    // hook has rewritten the table, the module on disk still does. The table patch is the fallback
    // and has only the re-entry guard between it and the recursion the first Windows run died of.
    {
        char why[512] = {};
        void* current = self.swapchain_vtable[slot_present];
        void* genuine = genuine_slot(self.swapchain_vtable, slot_present, current, why,
                                     sizeof(why));
        if (!genuine || !install_present_detour(self, genuine, why, sizeof(why))) {
            if (self.options.log) {
                char message[768];
                std::snprintf(message, sizeof(message),
                              "observer: Present is hooked in the swap chain's table, because %s. "
                              "If another hook chains back into this one, the inner call is "
                              "refused rather than recursed",
                              why);
                self.options.log(self.options.log_user, message);
            }
            if (!patch_slot(self.swapchain_vtable, slot_present,
                            reinterpret_cast<void*>(&hooked_present),
                            reinterpret_cast<void**>(&self.original_present))) {
                patch_slot(self.device_vtable, slot_create_texture2d,
                           reinterpret_cast<void*>(self.original_create), nullptr);
                return RSF_OBSERVER_ERROR_PATCH_FAILED;
            }
        }
    }

    // Only patched when something asked to be told. These run on the game's creation path for every
    // pipeline object it builds, and a hook that reports to nobody is pure cost. Each is
    // independent: a failure to patch one leaves the others in place and is reported by the
    // corresponding original staying null, because none of the three is worth failing install over.
    if (self.options.on_layout) {
        patch_slot(self.device_vtable, slot_create_input_layout,
                   reinterpret_cast<void*>(&hooked_create_input_layout),
                   reinterpret_cast<void**>(&self.original_create_input_layout));
    }
    if (self.options.on_shader) {
        patch_slot(self.device_vtable, slot_create_vertex_shader,
                   reinterpret_cast<void*>(&hooked_create_vertex_shader),
                   reinterpret_cast<void**>(&self.original_create_vertex_shader));
        patch_slot(self.device_vtable, slot_create_pixel_shader,
                   reinterpret_cast<void*>(&hooked_create_pixel_shader),
                   reinterpret_cast<void**>(&self.original_create_pixel_shader));
    }

    self.installed = true;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_uninstall(void)
{
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (!self.installed) {
        return RSF_OBSERVER_ERROR_NOT_READY;
    }
    patch_slot(self.device_vtable, slot_create_texture2d,
               reinterpret_cast<void*>(self.original_create), nullptr);
    if (self.original_create_buffer) {
        patch_slot(self.device_vtable, slot_create_buffer,
                   reinterpret_cast<void*>(self.original_create_buffer), nullptr);
        self.original_create_buffer = nullptr;
    }
    if (self.original_create_input_layout) {
        patch_slot(self.device_vtable, slot_create_input_layout,
                   reinterpret_cast<void*>(self.original_create_input_layout), nullptr);
        self.original_create_input_layout = nullptr;
    }
    if (self.original_create_vertex_shader) {
        patch_slot(self.device_vtable, slot_create_vertex_shader,
                   reinterpret_cast<void*>(self.original_create_vertex_shader), nullptr);
        self.original_create_vertex_shader = nullptr;
    }
    if (self.original_create_pixel_shader) {
        patch_slot(self.device_vtable, slot_create_pixel_shader,
                   reinterpret_cast<void*>(self.original_create_pixel_shader), nullptr);
        self.original_create_pixel_shader = nullptr;
    }
    if (self.present_detoured) {
        MH_DisableHook(self.present_entry);
        MH_RemoveHook(self.present_entry);
        self.present_detoured = false;
        self.present_entry = nullptr;
        self.present_chain = nullptr;
        self.present_genuine = nullptr;
        self.present_displaced = nullptr;
        // Not freed. A Present already inside the trampoline when the hook came off would return
        // into released memory, and sixty-four bytes for the life of the process are nothing.
        self.present_genuine_block = nullptr;
    } else if (self.original_present) {
        patch_slot(self.swapchain_vtable, slot_present,
                   reinterpret_cast<void*>(self.original_present), nullptr);
    }
    for (ID3D11Texture2D* texture : self.matches) {
        texture->Release();
    }
    self.matches.clear();
    for (auto& entry : self.constants) {
        entry.buffer->Release();
    }
    self.constants.clear();
    if (self.context) {
        self.context->Release();
        self.context = nullptr;
    }
    if (self.device) {
        self.device->Release();
        self.device = nullptr;
    }
    self.installed = false;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_acquire_device(void** device_out, void** context_out)
{
    if (!device_out && !context_out) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();

    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        if (!self.device) {
            return RSF_OBSERVER_ERROR_NOT_READY;
        }
        device = self.device;
        device->AddRef();
        context = self.context;
        if (context) {
            context->AddRef();
        }
    }

    // Resolved outside the lock for the same reason everything else here is: this calls into D3D11,
    // and D3D11 can re-enter the creation hook, which takes this mutex.
    if (!context && context_out) {
        device->GetImmediateContext(&context);
        if (context) {
            std::lock_guard<std::mutex> lock(self.guard);
            if (!self.context) {
                self.context = context;
                self.context->AddRef();
            }
        }
    }

    if (device_out) {
        *device_out = device;
    } else {
        device->Release();
    }
    if (context_out) {
        *context_out = context;
    } else if (context) {
        context->Release();
    }
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_get_status(rsf_observer_status* status)
{
    if (!status || status->struct_size < sizeof(rsf_observer_status)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    status->installed = self.installed ? 1u : 0u;
    status->have_device = self.device != nullptr ? 1u : 0u;
    status->frames_presented = self.frames;
    status->textures_matched = static_cast<uint32_t>(self.matches.size());
    status->textures_created = self.created;
    status->present_width = self.present_width;
    status->present_height = self.present_height;
    status->constant_buffers_matched = self.constant_matches;
    status->distinct_buffer_sizes = static_cast<uint32_t>(self.buffer_sizes.size());
    status->dumps_completed = self.dumps_completed;
    status->textures_written = self.textures_written;
    status->constant_bytes_written = self.constant_bytes_written;
    return RSF_OBSERVER_OK;
}


extern "C" rsf_observer_result rsf_observer_request_dump(const char* output_prefix_utf8,
                                                        uint32_t view)
{
    if (!output_prefix_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (!self.installed) {
        return RSF_OBSERVER_ERROR_NOT_READY;
    }
    self.dump_prefix = output_prefix_utf8;
    self.dump_view = view;
    self.dump_pending = true;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_write_buffer_sizes(const char* output_path_utf8)
{
    if (!output_path_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::vector<std::pair<uint32_t, uint32_t>> sizes;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        sizes = self.buffer_sizes;
    }
    std::FILE* stream = std::fopen(output_path_utf8, "wb");
    if (!stream) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    std::fprintf(stream, "bytes,created\n");
    for (const auto& entry : sizes) {
        std::fprintf(stream, "%u,%u\n", entry.first, entry.second);
    }
    std::fclose(stream);
    return RSF_OBSERVER_OK;
}
