// SPDX-License-Identifier: GPL-3.0-only

#include <rescaleframe/d3d11_observer.h>
#include <rescaleframe/motion_decode.h>
#include <rescaleframe/texture_dump.h>

#include <windows.h>

#include <d3d11.h>

#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

namespace {

// Vtable slots, from the table generated by tools/ghidra/build-directx-types.py.
constexpr size_t slot_create_buffer = 3;     // ID3D11Device
constexpr size_t slot_create_texture2d = 5;  // ID3D11Device
constexpr size_t slot_present = 8;           // IDXGISwapChain

using create_buffer_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*, const D3D11_BUFFER_DESC*,
                                                     const D3D11_SUBRESOURCE_DATA*,
                                                     ID3D11Buffer**);
using create_texture2d_fn = HRESULT(STDMETHODCALLTYPE*)(ID3D11Device*,
                                                        const D3D11_TEXTURE2D_DESC*,
                                                        const D3D11_SUBRESOURCE_DATA*,
                                                        ID3D11Texture2D**);
using present_fn = HRESULT(STDMETHODCALLTYPE*)(IDXGISwapChain*, UINT, UINT);

struct Observer {
    std::mutex guard;
    bool installed = false;

    void** device_vtable = nullptr;
    void** swapchain_vtable = nullptr;
    create_texture2d_fn original_create = nullptr;
    create_buffer_fn original_create_buffer = nullptr;
    present_fn original_present = nullptr;

    rsf_observer_options options{};

    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    std::vector<ID3D11Texture2D*> matches;

    struct SizedBuffer {
        uint32_t bytes;
        ID3D11Buffer* buffer;
    };
    std::vector<SizedBuffer> constants;
    std::vector<std::pair<uint32_t, uint32_t>> buffer_sizes;  // size, times created
    uint32_t constant_matches = 0;

    // A dump requested from another thread, performed inside the next present.
    bool dump_pending = false;
    std::string dump_prefix;
    uint32_t dump_view = 0;
    uint32_t dumps_completed = 0;
    uint32_t textures_written = 0;
    uint32_t constant_bytes_written = 0;

    uint32_t frames = 0;
    uint32_t created = 0;
    uint32_t present_width = 0;
    uint32_t present_height = 0;
};

Observer& observer()
{
    static Observer instance;
    return instance;
}

bool patch_slot(void** vtable, size_t index, void* replacement, void** previous)
{
    DWORD protection = 0;
    if (!VirtualProtect(&vtable[index], sizeof(void*), PAGE_EXECUTE_READWRITE, &protection)) {
        return false;
    }
    if (previous) {
        *previous = vtable[index];
    }
    vtable[index] = replacement;
    DWORD restored = 0;
    VirtualProtect(&vtable[index], sizeof(void*), protection, &restored);
    return true;
}

bool interesting(const D3D11_TEXTURE2D_DESC& desc, const rsf_observer_options& options)
{
    if ((desc.BindFlags & D3D11_BIND_RENDER_TARGET) == 0) {
        return false;
    }
    if (options.format != 0 && desc.Format != static_cast<DXGI_FORMAT>(options.format)) {
        return false;
    }
    return desc.Width >= options.minimum_width;
}

HRESULT STDMETHODCALLTYPE hooked_create_texture2d(ID3D11Device* device,
                                                  const D3D11_TEXTURE2D_DESC* desc,
                                                  const D3D11_SUBRESOURCE_DATA* initial,
                                                  ID3D11Texture2D** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }

    // Nothing below calls into D3D11 while the lock is held. This hook runs inside the runtime's
    // own texture creation, so any D3D call made here can re-enter it, and re-entering a
    // non-recursive mutex deadlocks the process. Record only, and resolve the device later.
    std::lock_guard<std::mutex> lock(self.guard);
    ++self.created;
    if (self.matches.size() < self.options.capacity && interesting(*desc, self.options)) {
        // Hold a reference so the target stays alive to be dumped later. Only a handful match,
        // so this does not meaningfully change the game's memory behaviour.
        (*out)->AddRef();
        self.matches.push_back(*out);
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    return result;
}

HRESULT STDMETHODCALLTYPE hooked_create_buffer(ID3D11Device* device,
                                               const D3D11_BUFFER_DESC* desc,
                                               const D3D11_SUBRESOURCE_DATA* initial,
                                               ID3D11Buffer** out)
{
    Observer& self = observer();
    const HRESULT result = self.original_create_buffer(device, desc, initial, out);
    if (FAILED(result) || !desc || !out || !*out) {
        return result;
    }
    if (self.options.constant_buffer_max_bytes == 0 ||
        (desc->BindFlags & D3D11_BIND_CONSTANT_BUFFER) == 0) {
        return result;
    }
    const uint32_t bytes = desc->ByteWidth;

    ID3D11Buffer* previous = nullptr;
    bool retain = bytes >= self.options.constant_buffer_min_bytes &&
                  bytes <= self.options.constant_buffer_max_bytes;
    if (retain) {
        (*out)->AddRef();
    }
    {
        std::lock_guard<std::mutex> lock(self.guard);
        // Every size is counted, whether retained or not. When the stock size does not match,
        // this histogram is what identifies the right buffer for the next run.
        bool counted = false;
        for (auto& entry : self.buffer_sizes) {
            if (entry.first == bytes) {
                ++entry.second;
                counted = true;
                break;
            }
        }
        if (!counted && self.buffer_sizes.size() < 128) {
            self.buffer_sizes.emplace_back(bytes, 1u);
        }

        if (retain) {
            // Keep the most recent buffer of each distinct size. Contents change every frame, so
            // an older one would describe a frame nobody asked about.
            bool replaced = false;
            for (auto& entry : self.constants) {
                if (entry.bytes == bytes) {
                    previous = entry.buffer;
                    entry.buffer = *out;
                    replaced = true;
                    break;
                }
            }
            if (!replaced) {
                if (self.constants.size() < 16) {
                    self.constants.push_back({bytes, *out});
                } else {
                    previous = *out;  // nothing left to hold it in
                    retain = false;
                }
            }
            if (retain) {
                ++self.constant_matches;
            }
        }
        if (!self.device) {
            self.device = device;
            self.device->AddRef();
        }
    }
    if (previous) {
        previous->Release();
    }
    return result;
}

// Read without the lock, which is safe because options are written once during install and never
// again, and necessary because the interesting lines come from inside the dump loop.
void say(const Observer& self, const char* format, ...)
{
    if (!self.options.log) {
        return;
    }
    char message[512];
    va_list arguments;
    va_start(arguments, format);
    std::vsnprintf(message, sizeof(message), format, arguments);
    va_end(arguments);
    self.options.log(self.options.log_user, message);
}

// Decode one target the way a backend needs it, and write the result beside the raw dump.
//
// The pass is built and thrown away per texture rather than kept. This runs on a key press a few
// times a session, so the cost does not matter, and a cached pass would have to be invalidated
// whenever the render size changed, which is exactly what this project makes happen.
void decode_and_dump(Observer& self, ID3D11Device* device, ID3D11DeviceContext* context,
                     ID3D11Texture2D* source, const char* prefix)
{
    D3D11_TEXTURE2D_DESC description{};
    source->GetDesc(&description);

    rsf_motion_decode_setup setup{};
    setup.struct_size = sizeof(setup);
    setup.abi_version = RSF_MOTION_DECODE_ABI_VERSION;
    setup.width = description.Width;
    setup.height = description.Height;
    setup.log = self.options.log;
    setup.log_user = self.options.log_user;

    rsf_motion_decode* pass = nullptr;
    const rsf_motion_decode_result made = rsf_motion_decode_create(device, &setup, &pass);
    if (made != RSF_MOTION_DECODE_OK || !pass) {
        say(self, "motion decode unavailable, result %d", int(made));
        return;
    }

    rsf_motion_decode_params params{};
    params.struct_size = sizeof(params);
    params.scale_x = self.options.motion_scale;
    params.scale_y = self.options.motion_scale;
    params.bias_x = self.options.motion_bias;
    params.bias_y = self.options.motion_bias;
    params.output_scale_x = 1.0f;
    params.output_scale_y = 1.0f;
    params.invalid_value = self.options.motion_invalid_value;
    params.zero_means_unwritten = 1;

    const rsf_motion_decode_result ran = rsf_motion_decode_run(pass, context, source, &params);
    if (ran != RSF_MOTION_DECODE_OK) {
        say(self, "motion decode refused, result %d", int(ran));
        rsf_motion_decode_destroy(pass);
        return;
    }

    char path[1024];
    std::snprintf(path, sizeof(path), "%s_decoded", prefix);
    rsf_texture_dump_options dump{};
    dump.struct_size = sizeof(dump);
    dump.abi_version = RSF_TEXTURE_DUMP_ABI_VERSION;
    dump.output_prefix_utf8 = path;
    dump.view = RSF_DUMP_VIEW_DECODED_MOTION;
    dump.log = self.options.log;
    dump.log_user = self.options.log_user;
    rsf_dump_texture(device, context, rsf_motion_decode_texture(pass), &dump, nullptr);
    rsf_motion_decode_destroy(pass);
}

// Performed on the presenting thread, where using the immediate context is safe.
void perform_pending_dump(Observer& self)
{
    std::string prefix;
    uint32_t view = 0;
    std::vector<ID3D11Texture2D*> textures;
    std::vector<Observer::SizedBuffer> buffers;
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        if (!self.dump_pending || !self.device) {
            return;
        }
        self.dump_pending = false;
        prefix = self.dump_prefix;
        view = self.dump_view;
        textures = self.matches;
        buffers = self.constants;
        device = self.device;
        device->AddRef();
        context = self.context;
        if (context) {
            context->AddRef();
        }
        for (ID3D11Texture2D* texture : textures) {
            texture->AddRef();
        }
        for (auto& entry : buffers) {
            entry.buffer->AddRef();
        }
    }

    if (!context) {
        device->GetImmediateContext(&context);
        if (context) {
            std::lock_guard<std::mutex> lock(self.guard);
            if (!self.context) {
                self.context = context;
                self.context->AddRef();
            }
        }
    }

    uint32_t written = 0;
    uint32_t constant_bytes = 0;
    say(self, "dump begin: %zu textures, %zu constant buffers", textures.size(), buffers.size());
    if (context) {
        for (size_t index = 0; index < textures.size(); ++index) {
            char path[1024];
            std::snprintf(path, sizeof(path), "%s_%zu", prefix.c_str(), index);
            rsf_texture_dump_options dump{};
            dump.struct_size = sizeof(dump);
            dump.abi_version = RSF_TEXTURE_DUMP_ABI_VERSION;
            dump.output_prefix_utf8 = path;
            dump.view = view;
            dump.log = self.options.log;
            dump.log_user = self.options.log_user;
            say(self, "texture %zu of %zu", index + 1, textures.size());
            const rsf_dump_texture_result result =
                rsf_dump_texture(device, context, textures[index], &dump, nullptr);
            if (result == RSF_TEXTURE_OK) {
                ++written;
            } else {
                say(self, "texture %zu refused, result %d", index + 1, int(result));
            }

            if (self.options.decode_motion) {
                decode_and_dump(self, device, context, textures[index], path);
            }
        }

        for (const auto& entry : buffers) {
            say(self, "constant buffer of %u bytes", entry.bytes);
            // Same rule as for textures: a copy between resources of different devices is invalid
            // and crashes rather than failing.
            ID3D11Device* owner = nullptr;
            entry.buffer->GetDevice(&owner);
            const bool same_device = owner == device;
            if (owner) {
                owner->Release();
            }
            if (!same_device) {
                say(self, "constant buffer skipped, it belongs to another device");
                continue;
            }

            D3D11_BUFFER_DESC staging{};
            entry.buffer->GetDesc(&staging);
            staging.Usage = D3D11_USAGE_STAGING;
            staging.BindFlags = 0;
            staging.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
            staging.MiscFlags = 0;
            ID3D11Buffer* readable = nullptr;
            if (SUCCEEDED(device->CreateBuffer(&staging, nullptr, &readable)) && readable) {
                context->CopyResource(readable, entry.buffer);
                D3D11_MAPPED_SUBRESOURCE mapped{};
                if (SUCCEEDED(context->Map(readable, 0, D3D11_MAP_READ, 0, &mapped))) {
                    char path[1024];
                    std::snprintf(path, sizeof(path), "%s_cb%u.bin", prefix.c_str(), entry.bytes);
                    if (std::FILE* stream = std::fopen(path, "wb")) {
                        std::fwrite(mapped.pData, 1, entry.bytes, stream);
                        std::fclose(stream);
                        constant_bytes += entry.bytes;
                    }
                    context->Unmap(readable, 0);
                }
                readable->Release();
            }
        }
        context->Release();
    } else {
        say(self, "dump abandoned: no device context");
    }

    say(self, "dump end: %u textures, %u constant bytes", written, constant_bytes);
    for (ID3D11Texture2D* texture : textures) {
        texture->Release();
    }
    for (auto& entry : buffers) {
        entry.buffer->Release();
    }
    device->Release();

    std::lock_guard<std::mutex> lock(self.guard);
    ++self.dumps_completed;
    self.textures_written = written;
    self.constant_bytes_written = constant_bytes;
}

HRESULT STDMETHODCALLTYPE hooked_present(IDXGISwapChain* swapchain, UINT interval, UINT flags)
{
    Observer& self = observer();

    bool need_details = false;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        ++self.frames;
        need_details = self.present_width == 0;
    }

    // Queried outside the lock for the same re-entrancy reason as the creation hook.
    if (need_details) {
        DXGI_SWAP_CHAIN_DESC desc{};
        const bool described = SUCCEEDED(swapchain->GetDesc(&desc));
        ID3D11Device* device = nullptr;
        // A device reached this way covers the case where every texture predates installation.
        swapchain->GetDevice(__uuidof(ID3D11Device), reinterpret_cast<void**>(&device));

        std::lock_guard<std::mutex> lock(self.guard);
        if (described && self.present_width == 0) {
            self.present_width = desc.BufferDesc.Width;
            self.present_height = desc.BufferDesc.Height;
        }
        if (device) {
            if (!self.device) {
                self.device = device;
            } else {
                device->Release();
            }
        }
    }
    perform_pending_dump(self);
    return self.original_present(swapchain, interval, flags);
}

// A dummy device and swap chain exist only to reach the vtables, which are shared by every
// instance the runtime creates. Once patched they can be released.
bool acquire_vtables(void*** device_vtable, void*** swapchain_vtable)
{
    WNDCLASSEXW window_class{};
    window_class.cbSize = sizeof(window_class);
    window_class.lpfnWndProc = DefWindowProcW;
    window_class.hInstance = GetModuleHandleW(nullptr);
    window_class.lpszClassName = L"RsfObserverProbe";
    RegisterClassExW(&window_class);
    HWND window = CreateWindowExW(0, window_class.lpszClassName, L"", WS_OVERLAPPEDWINDOW, 0, 0,
                                  8, 8, nullptr, nullptr, window_class.hInstance, nullptr);
    if (!window) {
        return false;
    }

    DXGI_SWAP_CHAIN_DESC desc{};
    desc.BufferCount = 1;
    desc.BufferDesc.Width = 8;
    desc.BufferDesc.Height = 8;
    desc.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    desc.OutputWindow = window;
    desc.SampleDesc.Count = 1;
    desc.Windowed = TRUE;

    IDXGISwapChain* swapchain = nullptr;
    ID3D11Device* device = nullptr;
    ID3D11DeviceContext* context = nullptr;
    const D3D_FEATURE_LEVEL wanted[] = {D3D_FEATURE_LEVEL_11_0};
    D3D_FEATURE_LEVEL obtained{};
    HRESULT created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
                                                    wanted, 1, D3D11_SDK_VERSION, &desc,
                                                    &swapchain, &device, &obtained, &context);
    if (FAILED(created)) {
        created = D3D11CreateDeviceAndSwapChain(nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0, wanted,
                                                1, D3D11_SDK_VERSION, &desc, &swapchain, &device,
                                                &obtained, &context);
    }
    if (FAILED(created) || !swapchain || !device) {
        DestroyWindow(window);
        return false;
    }

    *device_vtable = *reinterpret_cast<void***>(device);
    *swapchain_vtable = *reinterpret_cast<void***>(swapchain);

    if (context) {
        context->Release();
    }
    swapchain->Release();
    device->Release();
    DestroyWindow(window);
    return true;
}

} // namespace

extern "C" rsf_observer_result rsf_observer_install(const rsf_observer_options* options)
{
    if (!options || options->struct_size < sizeof(rsf_observer_options)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    if (options->abi_version != RSF_OBSERVER_ABI_VERSION) {
        return RSF_OBSERVER_ERROR_ABI_MISMATCH;
    }

    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (self.installed) {
        return RSF_OBSERVER_ERROR_ALREADY_INSTALLED;
    }

    self.options = *options;
    if (self.options.capacity == 0) {
        self.options.capacity = 16;
    }

    if (!acquire_vtables(&self.device_vtable, &self.swapchain_vtable)) {
        return RSF_OBSERVER_ERROR_NO_DEVICE;
    }

    if (!patch_slot(self.device_vtable, slot_create_texture2d,
                    reinterpret_cast<void*>(&hooked_create_texture2d),
                    reinterpret_cast<void**>(&self.original_create))) {
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    if (self.options.constant_buffer_max_bytes != 0 &&
        !patch_slot(self.device_vtable, slot_create_buffer,
                    reinterpret_cast<void*>(&hooked_create_buffer),
                    reinterpret_cast<void**>(&self.original_create_buffer))) {
        patch_slot(self.device_vtable, slot_create_texture2d,
                   reinterpret_cast<void*>(self.original_create), nullptr);
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }
    if (!patch_slot(self.swapchain_vtable, slot_present,
                    reinterpret_cast<void*>(&hooked_present),
                    reinterpret_cast<void**>(&self.original_present))) {
        patch_slot(self.device_vtable, slot_create_texture2d,
                   reinterpret_cast<void*>(self.original_create), nullptr);
        return RSF_OBSERVER_ERROR_PATCH_FAILED;
    }

    self.installed = true;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_uninstall(void)
{
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (!self.installed) {
        return RSF_OBSERVER_ERROR_NOT_READY;
    }
    patch_slot(self.device_vtable, slot_create_texture2d,
               reinterpret_cast<void*>(self.original_create), nullptr);
    if (self.original_create_buffer) {
        patch_slot(self.device_vtable, slot_create_buffer,
                   reinterpret_cast<void*>(self.original_create_buffer), nullptr);
        self.original_create_buffer = nullptr;
    }
    patch_slot(self.swapchain_vtable, slot_present, reinterpret_cast<void*>(self.original_present),
               nullptr);
    for (ID3D11Texture2D* texture : self.matches) {
        texture->Release();
    }
    self.matches.clear();
    for (auto& entry : self.constants) {
        entry.buffer->Release();
    }
    self.constants.clear();
    if (self.context) {
        self.context->Release();
        self.context = nullptr;
    }
    if (self.device) {
        self.device->Release();
        self.device = nullptr;
    }
    self.installed = false;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_get_status(rsf_observer_status* status)
{
    if (!status || status->struct_size < sizeof(rsf_observer_status)) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    status->installed = self.installed ? 1u : 0u;
    status->have_device = self.device != nullptr ? 1u : 0u;
    status->frames_presented = self.frames;
    status->textures_matched = static_cast<uint32_t>(self.matches.size());
    status->textures_created = self.created;
    status->present_width = self.present_width;
    status->present_height = self.present_height;
    status->constant_buffers_matched = self.constant_matches;
    status->distinct_buffer_sizes = static_cast<uint32_t>(self.buffer_sizes.size());
    status->dumps_completed = self.dumps_completed;
    status->textures_written = self.textures_written;
    status->constant_bytes_written = self.constant_bytes_written;
    return RSF_OBSERVER_OK;
}


extern "C" rsf_observer_result rsf_observer_request_dump(const char* output_prefix_utf8,
                                                        uint32_t view)
{
    if (!output_prefix_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::lock_guard<std::mutex> lock(self.guard);
    if (!self.installed) {
        return RSF_OBSERVER_ERROR_NOT_READY;
    }
    self.dump_prefix = output_prefix_utf8;
    self.dump_view = view;
    self.dump_pending = true;
    return RSF_OBSERVER_OK;
}

extern "C" rsf_observer_result rsf_observer_write_buffer_sizes(const char* output_path_utf8)
{
    if (!output_path_utf8) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    Observer& self = observer();
    std::vector<std::pair<uint32_t, uint32_t>> sizes;
    {
        std::lock_guard<std::mutex> lock(self.guard);
        sizes = self.buffer_sizes;
    }
    std::FILE* stream = std::fopen(output_path_utf8, "wb");
    if (!stream) {
        return RSF_OBSERVER_ERROR_INVALID_ARGUMENT;
    }
    std::fprintf(stream, "bytes,created\n");
    for (const auto& entry : sizes) {
        std::fprintf(stream, "%u,%u\n", entry.first, entry.second);
    }
    std::fclose(stream);
    return RSF_OBSERVER_OK;
}
