name: Verify

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install pinned Rust toolchain
        shell: pwsh
        run: rustup show
      - name: Verify native and Rust components
        shell: pwsh
        run: ./eng/verify.ps1 -Configuration Release
